### ISSUE TITLE
Add a way to choose planning frame to RobotCommander

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr_interface#103]
Currently `plan_to_waypoints_target` takes poses, and not StampedPoses (due to the underlying `compute_cartesian_path`).

We should allow the user to specify what is the planning frame, so that the Poses can be used in a sensible way.

Otherwise (like it happens in the `sr-right_hand_follow_finger_trajectory` example) the poses are dependant on the robot URDF. E.g. the pose of the fingertip is relative to the base of the robot, but the base (world) will probably the forearm base if it's a hand, or the arm base if it's a hand+arm. Also, the pose of the finger tip w.r.t. the base of the hand is different for a hand E than for a hand lite.

The easiest fix seems to be to allow the user to set the desired frame from the script before planning.

**Comment by ugocupcic** [comment]
take them as arguments to the method? And if no arguments is provided use the urdf defaults?
