### ISSUE TITLE
get_current_pose method of robot_commander is badly named

### ISSUE THREAD

**Issue by dg-shadow** [shadow-robot/sr_interface#104]
It should be called something like "get_movegroup_state"

Changing it will involve grepping a at least all of sr_interface to find places where the old style method is used. It's a relatively recent function so it's probably not used outside sr_interface anywhere yet.

**Comment by ugocupcic** [comment]
Why? I find `get_current_pose` easier to understand than `get_movegroup_state`.

**Comment by dg-shadow** [comment]
It's just that `pose` has a specific meaning (as in `geometry_msgs/Pose`). The information returned is a partial `RobotState` message...

**Comment by ugocupcic** [comment]
`get_current_state` then?

**Comment by dg-shadow** [comment]
but then there is a distinction between the state of the robot (whole state) and the state of the movegroup...

**Comment by ugocupcic** [comment]
but you're not using robot_commander directly you're using hand / arm commander right? So the movegroup is not something that the user needs to care about.

**Comment by dg-shadow** [comment]
Except that it is when you use the "whole robot" movegroup to move hand and arm together on the same in the same trajectory.

**Comment by dg-shadow** [comment]
https://github.com/shadow-robot/sr_interface/issues/93
