### ISSUE TITLE
Adapt sr_hand_finder_example.py for any hand

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr_interface#106]
Currently this example only works properly with a 24 joint hand.

**Comment by toliver** [comment]
Either use only named poses, or send a specific target to certain joints that are always present (e.g. FF joints).

**Comment by ugocupcic** [comment]
go with the latest - this is a basic example so named poses might make it slightly more complicated.

**Comment by toliver** [comment]
Actually it is already using some named poses. The only thing that doesn't work is the one that isn't named...
