### ISSUE TITLE
The kinematics plugin (right_arm) failed to load. 

### ISSUE THREAD

**Issue by MetaMemoryT** [shadow-robot/sr_interface#159]
indigo branch

```
[ERROR] [1461689978.739208039, 69.542000000]: The kinematics plugin (right_arm) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  hand_kinematics/HandKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin ur_kinematics/UR10KinematicsPlugin ur_kinematics/UR3KinematicsPlugin ur_kinematics/UR5KinematicsPlugin
[ERROR] [1461689978.739384984, 69.542000000]: Kinematics solver could not be instantiated for joint group right_arm.
[ERROR] [1461689978.739509619, 69.542000000]: The kinematics plugin (rh_wrist) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  hand_kinematics/HandKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin ur_kinematics/UR10KinematicsPlugin ur_kinematics/UR3KinematicsPlugin ur_kinematics/UR5KinematicsPlugin
[ERROR] [1461689978.739841546, 69.542000000]: Kinematics solver could not be instantiated for joint group rh_wrist.
```

I just did a manual git clone https://bitbucket.org/traclabs/trac_ik.git

and it seems to be fixed

**Comment by AndriyPt** [comment]
@MetaMemoryT you can find all dependencies which need to be installed from source code [here](https://github.com/shadow-robot/sr_interface/blob/indigo-devel/repository.rosinstall). We are using [the following one-liner script](http://shadow-robot.readthedocs.org/en/latest/generated/shadow_robot/INSTALL.html) to setup and update our workspaces with needed source code packages.

**Comment by MetaMemoryT** [comment]
I did use that, it must have not ran to completion, network disconnection issue maybe.  But I couldn't confirm that with the logs.

**Comment by AndriyPt** [comment]
this one liner script should create two workspaces. If you have executed default script then location of the workspace which has track_ik should be ~/projects/shadow_robot/base_deps/src . Please check that it was installed. Also check your .bashrc for correct sequence of the workspaces sourced. Maybe you has another workspace which has track_ik repo in it.
