### ISSUE TITLE
Use new place for definition of SetTeachMode service

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr_interface#218]
Change here

https://github.com/shadow-robot/sr_interface/blob/indigo-devel/sr_robot_launch/scripts/teach_mode_node#L9

To use the on defined in 

https://github.com/shadow-robot/sr_common/blob/indigo-devel/sr_robot_msgs/srv/SetTeachMode.srv

**Comment by mikramarc** [comment]
Fixed by PR #243
