### ISSUE TITLE
Trac_ik package on kinetics hasn't been released

### ISSUE THREAD

**Issue by beatrizleon** [shadow-robot/sr_interface#232]
Although it is already part of ros kinetic, ros-kinetic-trac-ik is not yet available.

Therefore we are keeping its dependency here:
https://github.com/shadow-robot/sr_interface/blob/kinetic-devel/repository.rosinstall

but it needs to be removed after the next ROS package sync.

**Comment by mikramarc** [comment]
Fixed by PR #243
