### ISSUE TITLE
warehouse servises should run for working with plugins

### ISSUE THREAD

**Issue by azompas** [shadow-robot/sr_interface#256]
the line below must be inserted in the hand's launch file:
<node name="warehouse_services" pkg="moveit_ros_warehouse" type="moveit_warehouse_services"/>

**Comment by beatrizleon** [comment]
it has been recently added:
https://github.com/shadow-robot/sr_interface/blob/kinetic-devel/sr_multi_moveit/sr_multi_moveit_config/launch/default_warehouse_db.launch#L20
