### ISSUE TITLE
Error in sr_ur_arm_hand.launch

### ISSUE THREAD

**Issue by kanishkaganguly** [shadow-robot/sr_interface#610]
Based on latest pull, there is an error in the `sr_ur_arm_hand.launch` file.

```bash
RLException: unused args [trajectory_controllers_list] for include of [/home/user/projects/shadow_robot/base/src/sr_interface/sr_multi_moveit/sr_multi_moveit_config/launch/moveit_planning_and_execution.launch]
The traceback for the exception was written to the log file
```

This appears to have been caused by [Line 205](https://github.com/shadow-robot/sr_interface/blob/melodic-devel/sr_robot_launch/launch/sr_ur_arm_hand.launch#L205) and commenting out that line fixes things.

**Comment by kanishkaganguly** [comment]
Similar issue exists for [Line 172](https://github.com/shadow-robot/sr_interface/blob/melodic-devel/sr_robot_launch/launch/sr_ur_arm_hand.launch#L172) with respect to the `hybrid_controller` parameter.

**Comment by biofotis** [comment]
Does this happen when you create your own controller?

**Comment by kanishkaganguly** [comment]
No, this was based on the vanilla launch file. However, based on the latest pull, I think this issue is sorted.
